version: '3'
services:
    app:
        image: lexal95/tourguide
        ports:
            - "3000:3000" 
        depends_on:
            - mongo
    mongo:
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - ./data:/data/db
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - "8081:8081"